---
title: "Compare"
author: "Wentao Zhan"
date: "2022/3/9"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F, warning = FALSE, echo = TRUE)
```

## R Markdown
```{r, echo = FALSE}
library(tidyverse)
library(reshape)

library(RColorBrewer)
group.colors <- c(brewer.pal(9,"Oranges")[c(4, 8)],
                  brewer.pal(9,"Greens")[c(5)], 
                  brewer.pal(9,"Blues")[c(4,8)])
names(group.colors) = c('NNGLS_oracle', 'NN-GLS', 
                        'NN-nonspatial',  
                        'NN-latlon', 'NN-spline')


group.colors <- c(brewer.pal(9,"YlOrRd")[c(3, 4, 5, 8)],
                       brewer.pal(9,"Reds")[c(3)],
                       brewer.pal(9,"Purples")[c(6)], 
                       brewer.pal(9,"Blues")[c(4,6,7)],
                       brewer.pal(8,"Set2")[c(5)], brewer.pal(9,"Greens")[c(7)])
names(group.colors) = c('NN-nonspatial', 'NN-latlon', 'NN-splines', 'NN-GLS',
                             'NN-GLS_oracle',
                             'Linear-spatial',
                             'GAM', 'GAM-latlon', 'GAMGLS',
                             'RF', 'RFGLS')
```

```{r}
ggsave('MISE_dim1_fix.png', width = 8, height = 6)
```

# 1010: sample size 1000/500, ordered
# 1011: sample size 2000/1000, unordered, only for Friedman
# 1018: added CI and PI, size 1000/500
# 1024: updated GAMGLS and sparse implementation. (only 5 dim now)

# 1120: tried to add intercept
# 1121: use sample size 5000/2500

# 1-dimensional case with 100 runs and seed. (script for 1010 and 1011)
```{r}
type = 'MISE'
func = 'friedman'
p = 5
date = '1120'
path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename_BRISC = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_BRISC_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){
        print('Not found')
        next}
      df_temp = read.csv(paste0(path, filename))[,-1]
      print(nrow(df_temp))
      df_temp$BRISC = read.csv(paste0(path, filename_BRISC))$BRISC[1:nrow(df_temp)]
      
      write.csv(df_temp, paste0(path, filename))
    }
  }
}
```

```{r}
type = 'MISE'
func = 'sin'
p = 1
date = '1125'
method = '0'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')
path2 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/1125/')

names = c('BRISC', 'GAM', 'GAMGLS', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'NN-nonspatial', 'NN-GLS')


data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
#print(list.files('./new_data'))
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename2 = paste0(c('p', p, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_MISE.csv'), collapse = '')
      filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_temp$NN = sqrt(read.csv(paste0(path, filename2))$MISE_DK1)
      df_temp$NNGLS = sqrt(read.csv(paste0(path, filename2))$MISE_GLS)
      df_RFGLS_temp = melt(read.csv(paste0(path2, filename3))[, c('RF', 'RFGLS')])
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
}
data = data[-1,]
data = data[complete.cases(data),]
df_RF = read.csv(paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/',
                        'Compare/RF_sin2000.csv'))[,-1]
if(F){
  data = data %>% filter(variable != 'RF')
  data_RF = data.frame(variable = rep('RF', nrow(df_RF)), value = df_RF$MISE, 
                       sigma_sq = df_RF$sigma, phi = round(df_RF$phi/sqrt(2),1), 
                       tau = df_RF$tau*100)  #%>% filter(sigma_sq == 5)
  data = rbind(data, data_RF)
}
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = mean(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'RFGLS', 'NN-nonspatial', 'NN-GLS')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
data_plt$MISE = pmin(data_plt$MISE, 0.5*data_plt$sigma_sq)

for (sigma_sq_temp in sigma_sq_vec){
  ggplot(data_plt %>% filter(sigma_sq == sigma_sq_temp), aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) + 
  xlab("tau %") + 
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
  figname = paste0(type, '_', func, '_sigma_sq', sigma_sq_temp, '_mtd', method, '_2000.png')
  ggsave(figname, width = 8, height = 3)
}
```

```{r}
type = 'MISE'
func = 'sin'
p = 1
date = '1121'
method = '0'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'GAM', 'GAMGLS', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'NN-nonspatial', 'NN-GLS')


data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
#print(list.files('./new_data'))
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, df_temp)
    }
  }
}
data = data[-1,]
data = data[complete.cases(data),]
df_RF = read.csv(paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/',
                        'Compare/RF_sin5000.csv'))[,-1]
if(T){
  data = data %>% filter(variable != 'RF')
  data_RF = data.frame(variable = rep('RF', nrow(df_RF)), value = df_RF$MISE, 
                       sigma_sq = df_RF$sigma, phi = round(df_RF$phi/sqrt(2),1), 
                       tau = df_RF$tau*100)  #%>% filter(sigma_sq == 5)
  data = rbind(data, data_RF)
}
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = mean(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'RFGLS', 'NN-nonspatial', 'NN-GLS')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
data_plt$MISE = pmin(data_plt$MISE, 0.4*data_plt$sigma_sq)
ggplot(data_plt , aes(x = tau, y = MISE)) + 
geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
scale_fill_manual(values=group.colors[names_alt]) + 
xlab("tau %") + scale_y_sqrt() +
facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
      axis.text=element_text(size=12), axis.title=element_text(size=15),
      strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
#figname = paste0(type, '_', func, '_sigma', sigma_sq_temp, '_mtd', method, '_2000.png')
#ggsave(figname, width = 8, height = 4)
```
```{r}
figname = paste0(type, '_', func, '_mtd', method, '_5000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
type = 'MISE'
func = 'sin'
p = 1
date = '1125'
method = '1'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'GAM', 'GAMGLS', 'RF', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'NN-nonspatial', 'NN-GLS')


data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
#print(list.files('./new_data'))
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_RFGLS_temp = melt(read.csv(paste0(path, filename3))[, c('RF', 'RFGLS')])
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
}
data = data[-1,]
data = data[complete.cases(data),]
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'RFGLS', 'NN-nonspatial', 'NN-GLS')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
data_plt$MISE = pmin(data_plt$MISE, 0.4*data_plt$sigma_sq)
ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) + 
  xlab("tau %") + 
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))

```
```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
type = 'MISE'
func = 'sin'
p = 1
date = '1201'
method = '2'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')
path2 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/1125/')

names = c('BRISC', 'GAM', 'GAMGLS', 'RF', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'NN-nonspatial', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
#print(list.files('./new_data'))
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_RFGLS_temp = melt(read.csv(paste0(path2, filename3))[, c('RF', 'RFGLS')])
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
}
data = data[-1,]
data = data[complete.cases(data),]
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'RFGLS', 'NN-nonspatial', 'NN-GLS')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
data_plt$MISE = pmin(data_plt$MISE, 0.4*data_plt$sigma_sq)
ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) + 
  xlab("tau %") + scale_y_sqrt() +
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))

```
```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 4)
```


# 1-dimensional case with 100 runs and seed. (script for 1018)

```{r}
type = 'PI_cov'
func = 'sin'
p = 1
date = '1125'
method = '0'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'NNGLS')
names_alt =  c('Linear-spatial', 'NN-GLS')


data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
#print(list.files('./new_data'))
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_RFGLS_temp = melt(read.csv(paste0(path, filename3))[, c('RF', 'RFGLS')])
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = mean(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt =  c('Linear-spatial', 'RFGLS', 'NN-GLS')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") + ylab("Interval coverage") + geom_hline(yintercept=0.95) +
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=20), legend.title = element_text(size=22),
        axis.text=element_text(size=18), axis.title=element_text(size=20),
        strip.text.x = element_text(size = 18), strip.text.y = element_text(size = 18))
```

```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 10, height = 5)
```


```{r}
type = 'PI_score'
func = 'sin'
p = 1
date = '1125'
method = '0'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'NNGLS')
names_alt =  c('Linear-spatial', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
#print(list.files('./new_data'))
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_RFGLS_temp = melt(read.csv(paste0(path, filename3))[, c('RF', 'RFGLS')])
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt =  c('Linear-spatial', 'RFGLS', 'NN-GLS')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") + ylab("Interval score") +
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=20), legend.title = element_text(size=22),
        axis.text=element_text(size=18), axis.title=element_text(size=20),
        strip.text.x = element_text(size = 18), strip.text.y = element_text(size = 18))
```

```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 10, height = 5)
```


```{r}
type = 'RMSE'
func = 'sin'
p = 1
date = '1125'
method = '0'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')
path2 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

namelist = list(c('BRISC', 'GAM_latlong', 'NN', 'NN_latlong', 'NNDK',  'NNGLS_krig'),
                c('BRISC', 'GAM', 'GAM_krig', 'GAMGLS', 'GAMGLS_krig', 'NNGLS_krig'),
                c('RF', 'RF_krig', 'RFGLS_krig','NNGLS_krig', 'NNGLS_krig'),
                c('NN', 'NN_latlong', 'NNDK', 'NN_krig', 'NNGLS_krig'))
classes = c('GAM', 'RF', 'NN')
for(t in 1:1){
  names = namelist[[t]]
  class = classes[t]
  names_alt = c('Linear-spatial', 'GAM-latlon', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')
  
  data = data.frame(matrix(ncol = 5))
  colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
  for(i in 1:length(sigma_sq_vec)){
    for(j in 1:length(phi_vec)){
      for(k in 1:length(tau_vec)){
        filename = paste0(c(func, 'phi', phi_vec[j], 
                            'sig', sigma_sq_vec[i], 
                            'tau', tau_vec[k], 
                            'mtd', method, '_', type, '.csv'), collapse = '')
        filename2 = paste0(c('p', p, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RMSE.csv'), collapse = '')
        filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS_', type, '.csv'), collapse = '')
        if(!(filename %in% list.files(path))){next}
        df_temp = read.csv(paste0(path, filename))[, names]
        df_temp$NNGLS_krig = read.csv(paste0(path, filename2))$NNGLS_krig
        df_temp$NN_latlong = read.csv(paste0(path, filename2))$DK
        df_RFGLS_temp = melt(read.csv(paste0(path2, filename3))[, c('RF', 'RFGLS')])
        df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
        df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
        df_RFGLS_temp$tau = tau_vec[k]
        colnames(df_temp) = names_alt
        df_temp = melt(df_temp)
        df_temp$sigma_sq = sigma_sq_vec[i]
        df_temp$phi = round(phi_vec[j]/sqrt(2),1)
        df_temp$tau = tau_vec[k]
        data = rbind(data, rbind(df_temp, df_RFGLS_temp))
      }
    }
    
  }
  data = data[-1,]
  data = data[complete.cases(data),]
  #data = data %>% filter(sigma_sq == 1 & phi == 0.7)
  data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% 
    summarise(value = median(value))
  colnames(data_plt)[4:5] = c('Method', 'MISE') 
  names_alt = c('Linear-spatial', 'GAM-latlon', 'RFGLS', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')
  data_plt = data_plt %>% filter(Method %in% names_alt)
  data_plt$Method = factor(data_plt$Method, levels = names_alt)
  data_plt$MISE = (data_plt$MISE)^2
  for (sigma_sq_temp in sigma_sq_vec){
  ggplot(data_plt %>% filter(sigma_sq == sigma_sq_temp), aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) + 
  xlab("tau %") + ylab("RMSE") + 
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
  figname = paste0(type, '_', func, '_sigma_sq', sigma_sq_temp, '_mtd', method, '_2000.png')
  ggsave(figname, width = 8, height = 3)
}
}

sigma_sq_temp = 1
data_plt$MISE = sapply(data_plt$MISE, function(x){min(x, 0.25)})
ggplot(data_plt %>% filter(sigma_sq == sigma_sq_temp), aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) + 
  xlab("tau %") + ylab("RMSE") + ylim(NA, 0.25) + 
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
  figname = paste0(type, '_', func, '_sigma_sq', sigma_sq_temp, '_mtd', method, '_2000.png')
  ggsave(figname, width = 8, height = 3)

```

```{r}
type = 'RMSE'
func = 'sin'
p = 1
date = '1125'
method = '0'
sigma_sq_vec = c(1)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')
path2 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/1125/')

namelist = list(c('BRISC', 'GAM_latlong', 'NN', 'NN_latlong', 'NNDK',  'NNGLS_krig'),
                c('BRISC', 'GAM', 'GAM_krig', 'GAMGLS', 'GAMGLS_krig', 'NNGLS_krig'),
                c('RF', 'RF_krig', 'RFGLS_krig','NNGLS_krig', 'NNGLS_krig'),
                c('NN', 'NN_latlong', 'NNDK', 'NN_krig', 'NNGLS_krig'))
classes = c('GAM', 'RF', 'NN')
for(i in 1:1){
  names = namelist[[i]]
  class = classes[i]
#names_alt = names
  names_alt = c('Linear-spatial', 'GAM-latlon', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
        filename = paste0(c(func, 'phi', phi_vec[j], 
                      'sig', sigma_sq_vec[i], 
                      'tau', tau_vec[k], 
                      'mtd', method, '_', type, '.csv'), collapse = '')
        filename2 = paste0(c('p', p, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RMSE.csv'), collapse = '')
        filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
        if(!(filename %in% list.files(path))){next}
        df_temp = read.csv(paste0(path, filename))[, names]
        df_temp$NNGLS_krig = read.csv(paste0(path, filename2))$NNGLS_krig
        df_temp$NN_latlong = read.csv(paste0(path, filename2))$DK
        df_RFGLS_temp = read.csv(paste0(path2, filename3))[, c('RF', 'RFGLS_krig')]
        colnames(df_RFGLS_temp) = c('RF', 'RFGLS')
        df_RFGLS_temp = melt(df_RFGLS_temp)
        df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
        df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
        df_RFGLS_temp$tau = tau_vec[k]
        colnames(df_temp) = names_alt
        df_temp = melt(df_temp)
        df_temp$sigma_sq = sigma_sq_vec[i]
        df_temp$phi = round(phi_vec[j]/sqrt(2),1)
        df_temp$tau = tau_vec[k]
        data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
data = data %>% filter(sigma_sq == 1 & phi == 0.7)
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt = c('Linear-spatial', 'GAM-latlon', 'RFGLS', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
data_plt$MISE = sapply(data_plt$MISE, function(x){min(x, 0.25)})
p = ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") + ylab("RMSE") + ylim(NA, 0.25) +
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
  print(p)
#figname = paste0(type, '_', func, '_mtd', method, '_vs_', class, '.png')
#ggsave(figname, width = 8, height = 6)
}

```

```{r}
figname = paste0('RMSE_dim1_main.png')
ggsave(figname, width = 8, height = 6)
```

```{r}
type = 'RMSE'
func = 'sin'
p = 1
date = '1121'
method = '0'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')
path2 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/RMSE/', p, 'dim/rand/')

namelist = list(c('BRISC', 'GAM_latlong', 'NN', 'NN_latlong', 'NNDK',  'NNGLS_krig'),
                c('BRISC', 'GAM', 'GAM_krig', 'GAMGLS', 'GAMGLS_krig', 'NNGLS_krig'),
                c('RF', 'RF_krig', 'RFGLS_krig','NNGLS_krig', 'NNGLS_krig'),
                c('NN', 'NN_latlong', 'NNDK', 'NN_krig', 'NNGLS_krig'))
classes = c('GAM', 'RF', 'NN')
for(t in 1:1){
  names = namelist[[t]]
  class = classes[t]
  names_alt = c('Linear-spatial', 'GAM-latlon', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')
  
  data = data.frame(matrix(ncol = 5))
  colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
  for(i in 1:length(sigma_sq_vec)){
    for(j in 1:length(phi_vec)){
      for(k in 1:length(tau_vec)){
        filename = paste0(c(func, 'phi', phi_vec[j], 
                            'sig', sigma_sq_vec[i], 
                            'tau', tau_vec[k], 
                            'mtd', method, '_', type, '.csv'), collapse = '')
      filename2 = paste0(c('p', p, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_rand.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_temp$NNGLS_krig = read.csv(paste0(path2, filename2))$NNGLS_krig[1:nrow(df_temp)]
      df_temp$NN_latlong = read.csv(paste0(path2, filename2))$DK[1:nrow(df_temp)]
      df_temp$NNDK = read.csv(paste0(path2, filename2))$DK_spline[1:nrow(df_temp)]
        colnames(df_temp) = names_alt
        df_temp = melt(df_temp)
        df_temp$sigma_sq = sigma_sq_vec[i]
        df_temp$phi = round(phi_vec[j]/sqrt(2),1)
        df_temp$tau = tau_vec[k]
        
        data = rbind(data, df_temp)
      }
    }
    
  }
  data = data[-1,]
  data = data[complete.cases(data),]
  data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% 
    summarise(value = median(value))
  colnames(data_plt)[4:5] = c('Method', 'MISE') 
  data_plt$Method = factor(data_plt$Method, levels = names_alt)
  data_plt$MISE = (data_plt$MISE)^2
  #data_plt$MISE = pmin(data_plt$MISE, 0.4*data_plt$sigma_sq)
  p = ggplot(data_plt, aes(x = tau, y = MISE)) + 
    geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
    scale_fill_manual(values=group.colors[names_alt]) +
    xlab("tau %") + ylab("RMSE") + scale_y_sqrt() +
    facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
    theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
          axis.text=element_text(size=12), axis.title=element_text(size=15),
          strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
    print(p)
  #figname = paste0(type, '_', func, '_mtd', method, '_vs_', class, '.png')
  #ggsave(figname, width = 8, height = 6)
}
```

```{r}
figname = paste0(type, '_', func, '_mtd', method, '_5000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
type = 'RMSE'
func = 'sin'
p = 1
date = '1125'
method = '1'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')
path2 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/RMSE/', p, 'dim/rand/')
path3 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/1125/')

namelist = list(c('BRISC', 'GAM_latlong', 'NN', 'NN_latlong', 'NNDK',  'NNGLS_krig'),
                c('BRISC', 'GAM', 'GAM_krig', 'GAMGLS', 'GAMGLS_krig', 'NNGLS_krig'),
                c('RF', 'RF_krig', 'RFGLS_krig','NNGLS_krig', 'NNGLS_krig'),
                c('NN', 'NN_latlong', 'NNDK', 'NN_krig', 'NNGLS_krig'))
classes = c('GAM', 'RF', 'NN')
for(t in 1:1){
  names = namelist[[t]]
  class = classes[t]
  names_alt = c('Linear-spatial', 'GAM-latlon', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')
  
  data = data.frame(matrix(ncol = 5))
  colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
  for(i in 1:length(sigma_sq_vec)){
    for(j in 1:length(phi_vec)){
      for(k in 1:length(tau_vec)){
        filename = paste0(c(func, 'phi', phi_vec[j], 
                            'sig', sigma_sq_vec[i], 
                            'tau', tau_vec[k], 
                            'mtd', method, '_', type, '.csv'), collapse = '')
      filename2 = paste0(c('p', p, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_rand.csv'), collapse = '')
      filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_temp$NNGLS_krig = read.csv(paste0(path2, filename2))$NNGLS_krig[1:nrow(df_temp)]
      df_temp$NN_latlong = read.csv(paste0(path2, filename2))$DK[1:nrow(df_temp)]
      df_temp$NNDK = read.csv(paste0(path2, filename2))$DK_spline[1:nrow(df_temp)]
      df_RFGLS_temp = read.csv(paste0(path3, filename3))[, c('RF', 'RFGLS_krig')]
      colnames(df_RFGLS_temp) = c('RF', 'RFGLS')
      df_RFGLS_temp = melt(df_RFGLS_temp)
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
      }
    }
    
  }
  data = data[-1,]
  data = data[complete.cases(data),]
  data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% 
    summarise(value = median(value))
  colnames(data_plt)[4:5] = c('Method', 'MISE') 
  names_alt = c('Linear-spatial', 'GAM-latlon', 'RFGLS', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')
  data_plt = data_plt %>% filter(Method %in% names_alt)
  data_plt$Method = factor(data_plt$Method, levels = names_alt)
  data_plt$MISE = (data_plt$MISE)^2
  data_plt$MISE = pmin(data_plt$MISE, 0.4*data_plt$sigma_sq)
  p = ggplot(data_plt, aes(x = tau, y = MISE)) + 
    geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
    scale_fill_manual(values=group.colors[names_alt]) +
    xlab("tau %") + ylab("RMSE") + scale_y_sqrt() +
    facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
    theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
          axis.text=element_text(size=12), axis.title=element_text(size=15),
          strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
    print(p)
  #figname = paste0(type, '_', func, '_mtd', method, '_vs_', class, '.png')
  #ggsave(figname, width = 8, height = 6)
}
```

```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
type = 'RMSE'
func = 'sin'
p = 1
date = '1201'
method = '2'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')
path2 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/RMSE/', p, 'dim/rand/')
path3 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/1125/')

namelist = list(c('BRISC', 'GAM_latlong', 'NN', 'NN_latlong', 'NNDK',  'NNGLS_krig'),
                c('BRISC', 'GAM', 'GAM_krig', 'GAMGLS', 'GAMGLS_krig', 'NNGLS_krig'),
                c('RF', 'RF_krig', 'RFGLS_krig','NNGLS_krig', 'NNGLS_krig'),
                c('NN', 'NN_latlong', 'NNDK', 'NN_krig', 'NNGLS_krig'))
classes = c('GAM', 'RF', 'NN')
for(t in 1:1){
  names = namelist[[t]]
  class = classes[t]
  names_alt = c('Linear-spatial', 'GAM-latlon', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')
  
  data = data.frame(matrix(ncol = 5))
  colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
  for(i in 1:length(sigma_sq_vec)){
    for(j in 1:length(phi_vec)){
      for(k in 1:length(tau_vec)){
        filename = paste0(c(func, 'phi', phi_vec[j], 
                            'sig', sigma_sq_vec[i], 
                            'tau', tau_vec[k], 
                            'mtd', method, '_', type, '.csv'), collapse = '')
      filename2 = paste0(c('p', p, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_rand.csv'), collapse = '')
      filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_temp$NNGLS_krig = read.csv(paste0(path2, filename2))$NNGLS_krig[1:nrow(df_temp)]
      df_temp$NN_latlong = read.csv(paste0(path2, filename2))$DK[1:nrow(df_temp)]
      df_temp$NNDK = read.csv(paste0(path2, filename2))$DK_spline[1:nrow(df_temp)]
      df_RFGLS_temp = read.csv(paste0(path3, filename3))[, c('RF', 'RFGLS_krig')]
      colnames(df_RFGLS_temp) = c('RF', 'RFGLS')
      df_RFGLS_temp = melt(df_RFGLS_temp)
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
      }
    }
    
  }
  data = data[-1,]
  data = data[complete.cases(data),]
  data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% 
    summarise(value = median(value))
  colnames(data_plt)[4:5] = c('Method', 'MISE') 
  names_alt = c('Linear-spatial', 'GAM-latlon', 'RFGLS', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')
  data_plt = data_plt %>% filter(Method %in% names_alt)
  data_plt$Method = factor(data_plt$Method, levels = names_alt)
  data_plt$MISE = (data_plt$MISE)^2
  data_plt$MISE = pmin(data_plt$MISE, 0.4*sqrt(data_plt$sigma_sq))
  p = ggplot(data_plt, aes(x = tau, y = MISE)) + 
    geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
    scale_fill_manual(values=group.colors[names_alt]) +
    xlab("tau %") + ylab("RMSE") + ylim(NA, 0.3) + scale_y_sqrt() +
    facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
    theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
          axis.text=element_text(size=12), axis.title=element_text(size=15),
          strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
    print(p)
  #figname = paste0(type, '_', func, '_mtd', method, '_vs_', class, '.png')
  #ggsave(figname, width = 8, height = 6)
}

```

```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 4)
```



```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 6)
```

# 5-dimensional case with 500 runs and seed.
```{r}
type = 'MISE'
func = 'friedman'
p = 5
date = '1125'
method = '0'
sigma_sq_vec = c(1)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')
path2 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/1201/')

names = c('BRISC', 'GAM', 'GAMGLS', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'NN-nonspatial', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename2 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      #df_temp$NN = sqrt(read.csv(paste0(path, filename2))$MISE_DK1)
      #df_temp$NNGLS = sqrt(read.csv(paste0(path, filename2))$MISE_GLS)
      df_RFGLS_temp = melt(read.csv(paste0(path, filename2))[, c('RF','RFGLS')])
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
df_RF = read.csv(paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/',
                        'Compare/RF_friedman2000.csv'))[,-1]
if(T){
  data = data %>% filter(variable != 'RF')
  data_RF = data.frame(variable = rep('RF', nrow(df_RF)), value = df_RF$MISE, 
                       sigma_sq = df_RF$sigma, phi = round(df_RF$phi/sqrt(2),1), 
                       tau = df_RF$tau*100) #%>% filter(sigma_sq == 5)
  data = rbind(data, data_RF)
}
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'RFGLS', 'NN-nonspatial', 'NN-GLS')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
for (sigma_sq_temp in sigma_sq_vec){
  ggplot(data_plt %>% filter(sigma_sq == sigma_sq_temp), aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) + 
  xlab("tau %") + 
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
  figname = paste0(type, '_', func, '_sigma_sq', sigma_sq_temp, '_mtd', method, '_2000.png')
  ggsave(figname, width = 8, height = 3)
}
```
```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 6)
```

```{r}
type = 'MISE'
func = 'friedman'
p = 5
date = '1125'
method = '1'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'GAM', 'GAMGLS', 'RF', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'NN-nonspatial', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_RFGLS_temp = melt(read.csv(paste0(path, filename3))[, c('RF', 'RFGLS')])
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
df_RF = read.csv(paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/',
                        'Compare/RF_friedman2000.csv'))[,-1]
if(F){
  data = data %>% filter(variable != 'RF')
  data_RF = data.frame(variable = rep('RF', nrow(df_RF)), value = df_RF$MISE, 
                       sigma_sq = df_RF$sigma_sq, phi = round(df_RF$phi/sqrt(2),1), 
                       tau = df_RF$tau*100) #%>% filter(sigma_sq == 5)
  data = rbind(data, data_RF)
}
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'RFGLS', 'NN-nonspatial', 'NN-GLS')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") +
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
figname = paste0(getwd(), '/', type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
figname = paste0(getwd(), '/', type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 4)
```

# 1201 gives correct specified fixed surface
```{r}
type = 'MISE'
func = 'friedman'
p = 5
date = '1125'
method = '2'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'GAM', 'GAMGLS', 'RF', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'NN-nonspatial', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_RFGLS_temp = melt(read.csv(paste0(path, filename3))[, c('RF', 'RFGLS')])
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
df_RF = read.csv(paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/',
                        'Compare/RF_friedman2000.csv'))[,-1]
if(F){
  data = data %>% filter(variable != 'RF')
  data_RF = data.frame(variable = rep('RF', nrow(df_RF)), value = df_RF$MISE, 
                       sigma_sq = df_RF$sigma_sq, phi = round(df_RF$phi/sqrt(2),1), 
                       tau = df_RF$tau*100) #%>% filter(sigma_sq == 5)
  data = rbind(data, data_RF)
}
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'RFGLS', 'NN-nonspatial', 'NN-GLS')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %")  + scale_y_sqrt() +
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
```

```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
type = 'MISE'
func = 'friedman'
p = 5
date = '1121'
method = '0'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'GAM', 'GAMGLS', 'RF', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'NN-nonspatial', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      #df_temp$NN = sqrt(read.csv(paste0(path, filename2))$MISE_DK1)
      #df_temp$NNGLS = sqrt(read.csv(paste0(path, filename2))$MISE_GLS)
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      
      data = rbind(data, df_temp)
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
df_RF = read.csv(paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/',
                        'Compare/RF_friedman5000.csv'))[,-1]
if(T){
  data = data %>% filter(variable != 'RF')
  data_RF = data.frame(variable = rep('RF', nrow(df_RF)), value = df_RF$MISE, 
                       sigma_sq = df_RF$sigma, phi = round(df_RF$phi/sqrt(2),1), 
                       tau = df_RF$tau*100)
  data = rbind(data, data_RF)
}
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") +
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
```
```{r}
figname = paste0(type, '_', func, '_mtd', method, '_5000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
type = 'MISE'
func = 'friedman'
p = 5
date = '1125'
method = '0'
sigma_sq_vec = c(1)
phi_vec = c(1)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')
path2 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/1125/')

names = c('BRISC', 'GAM', 'GAMGLS', 'RF', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'NN-nonspatial', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename2 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      #df_temp$NN = sqrt(read.csv(paste0(path, filename2))$MISE_DK1)
      #df_temp$NNGLS = sqrt(read.csv(paste0(path, filename2))$MISE_GLS)
      df_RFGLS_temp = melt(read.csv(paste0(path, filename2))[, c('RF','RFGLS')])
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
df_RF = read.csv(paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/',
                        'Compare/RF_friedman2000.csv'))[,-1]
if(T){
  data = data %>% filter(variable != 'RF')
  data_RF = data.frame(variable = rep('RF', nrow(df_RF)), value = df_RF$MISE, 
                       sigma_sq = df_RF$sigma, phi = round(df_RF$phi/sqrt(2),1), 
                       tau = df_RF$tau*100)
  data = rbind(data, data_RF)
}
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'RFGLS', 'NN-nonspatial', 'NN-GLS')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
data_plt %>% filter(phi == 0.7 & sigma_sq ==1) %>% ggplot(aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
```

```{r}
figname = paste0('MISE_dim5_main.png')
ggsave(figname, width = 8, height = 6)
```

```{r}
type = 'MISE'
func = 'friedman'
p = 5
date = '1125'
method = '0'
sigma_sq_vec = c(1, 5, 10)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

#names = c('BRISC', 'GAM', 'GAMGLS', 'RF', 'NN', 'NNGLS')
#names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'NN-nonspatial', 'NN-GLS')

names = c('NN', 'NNGLS')
names_alt = c('NN-nonspatial', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      
      data = rbind(data, df_temp)
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
df_RF = read.csv(paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/',
                        'Compare/RF_friedman2000.csv'))[,-1]
if(F){
  data = data %>% filter(variable != 'RF')
  data_RF = data.frame(variable = rep('RF', nrow(df_RF)), value = df_RF$MISE, 
                       sigma_sq = df_RF$sigma_sq, phi = round(df_RF$phi/sqrt(2),1), 
                       tau = df_RF$tau*100)
  data = rbind(data, data_RF)
}
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
data_plt %>% filter(tau == 1 & sigma_sq ==1) %>% ggplot(aes(x = phi, y = MISE)) + 
  geom_line(aes(color = Method), position = "dodge", stat="identity", size = 2) + 
  scale_color_manual(values=group.colors[names_alt]) +
  xlab("phi") +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
```

```{r}
figname = paste0('MISE_dim5_main_phi.png')
ggsave(figname, width = 8, height = 6)
```

```{r}
type = 'PI_cov'
func = 'friedman'
p = 5
date = '1125'
method = '0'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'NNGLS')
names_alt =  c('Linear-spatial', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
#print(list.files('./new_data'))
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      if(i == 1){
        filename2 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
        path2 = path 
      }
      else{
        filename2 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS_', type, '.csv'), collapse = '')
        path2 = path
      }
      #print(!(filename %in% list.files('./new_data')))
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_RFGLS_temp = melt(read.csv(paste0(path2, filename2))[, c('RF','RFGLS')])
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt =  c('Linear-spatial', 'RFGLS', 'NN-GLS')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") + ylab("Interval coverage") + geom_hline(yintercept=0.95) +
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=20), legend.title = element_text(size=22),
        axis.text=element_text(size=18), axis.title=element_text(size=20),
        strip.text.x = element_text(size = 18), strip.text.y = element_text(size = 18))
```

```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 10, height = 5)
```

```{r}
type = 'PI_score'
func = 'friedman'
p = 5
date = '1125'
method = '0'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'NNGLS')
names_alt =  c('Linear-spatial', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
#print(list.files('./new_data'))
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      if(i == 1){
        filename2 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
        path2 = path 
      }
      else{
        filename2 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS_', type, '.csv'), collapse = '')
        path2 = path
      }
      #print(!(filename %in% list.files('./new_data')))
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_RFGLS_temp = melt(read.csv(paste0(path2, filename2))[, c('RF','RFGLS')])
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt =  c('Linear-spatial', 'RFGLS', 'NN-GLS')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") + ylab("Interval coverage") +
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=20), legend.title = element_text(size=22),
        axis.text=element_text(size=18), axis.title=element_text(size=20),
        strip.text.x = element_text(size = 18), strip.text.y = element_text(size = 18))
```

```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 10, height = 5)
```

```{r}
type = 'RMSE'
func = 'friedman'
p = 5
date = '1125'
method = '0'
sigma_sq_vec = c(1) #Use RFGLS20 for sigma = 1
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')
path2 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

namelist = list(c('BRISC', 'GAM_latlong', 'NN', 'NN_latlong', 'NNDK',  'NNGLS_krig'),
                c('BRISC', 'GAM', 'GAM_krig', 'GAMGLS', 'GAMGLS_krig', 'NNGLS_krig'),
                c('RF', 'RF_krig', 'RFGLS_krig','NNGLS_krig', 'NNGLS_krig'),
                c('NN', 'NN_latlong', 'NNDK', 'NN_krig', 'NNGLS_krig'))
classes = c('GAM', 'RF', 'NN')
for(i in 1:1){
  names = namelist[[i]]
  class = classes[i]
#names_alt = names
  names_alt = c('Linear-spatial', 'GAM-latlon', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 
                      'sig', sigma_sq_vec[i], 
                      'tau', tau_vec[k], 
                      'mtd', method, '_', type, '.csv'), collapse = '')
        filename2 = paste0(c('p', p, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RMSE.csv'), collapse = '')
        filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
        if(!(filename %in% list.files(path))){next}
        df_temp = read.csv(paste0(path, filename))[, names]
        #df_temp$NNGLS_krig = read.csv(paste0(path, filename2))$NNGLS_krig
        #df_temp$NN_latlong = read.csv(paste0(path, filename2))$DK
        df_RFGLS_temp = read.csv(paste0(path2, filename3))[, c('RF', 'RFGLS_krig')]
        colnames(df_RFGLS_temp) = c('RF', 'RFGLS')
        df_RFGLS_temp = melt(df_RFGLS_temp)
        df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
        df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
        df_RFGLS_temp$tau = tau_vec[k]
        colnames(df_temp) = names_alt
        df_temp = melt(df_temp)
        df_temp$sigma_sq = sigma_sq_vec[i]
        df_temp$phi = round(phi_vec[j]/sqrt(2),1)
        df_temp$tau = tau_vec[k]
        data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt = c('Linear-spatial', 'GAM-latlon', 'RFGLS', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
for (sigma_sq_temp in sigma_sq_vec){
  ggplot(data_plt %>% filter(sigma_sq == sigma_sq_temp), aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) + 
  xlab("tau %") + ylab("RMSE") + 
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
  figname = paste0(type, '_', func, '_sigma_sq', sigma_sq_temp, '_mtd', method, '_2000.png')
  ggsave(figname, width = 8, height = 3)
}
}

```
```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
type = 'GMSE'
func = 'friedman'
p = 5
date = '1125'
method = '0'
sigma_sq_vec = c(1)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')
path2 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/1125/')

namelist = list(c('BRISC', 'GAM_latlong', 'NN', 'NN_latlong', 'NNDK',  'NNGLS_krig'),
                c('BRISC', 'GAM', 'GAM_krig', 'GAMGLS', 'GAMGLS_krig', 'NNGLS_krig'),
                c('RF', 'RF_krig', 'RFGLS_krig','NNGLS_krig', 'NNGLS_krig'),
                c('NN', 'NN_latlong', 'NNDK', 'NN_krig', 'NNGLS_krig'))
classes = c('GAM', 'RF', 'NN')
for(i in 1:1){
  names = namelist[[i]]
  class = classes[i]
#names_alt = names
  names_alt = c('Linear-spatial', 'GAM-latlon', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
        filename = paste0(c(func, 'phi', phi_vec[j], 
                      'sig', sigma_sq_vec[i], 
                      'tau', tau_vec[k], 
                      'mtd', method, '_', type, '.csv'), collapse = '')
        filename2 = paste0(c('p', p, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RMSE.csv'), collapse = '')
        filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
        if(!(filename %in% list.files(path))){next}
        df_temp = read.csv(paste0(path, filename))[, names]
        df_temp$NNGLS_krig = read.csv(paste0(path, filename2))$NNGLS_krig
        df_temp$NN_latlong = read.csv(paste0(path, filename2))$DK
        df_RFGLS_temp = read.csv(paste0(path2, filename3))[, c('RF', 'RFGLS_krig')]
        colnames(df_RFGLS_temp) = c('RF', 'RFGLS')
        df_RFGLS_temp = melt(df_RFGLS_temp)
        df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
        df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
        df_RFGLS_temp$tau = tau_vec[k]
        colnames(df_temp) = names_alt
        df_temp = melt(df_temp)
        df_temp$sigma_sq = sigma_sq_vec[i]
        df_temp$phi = round(phi_vec[j]/sqrt(2),1)
        df_temp$tau = tau_vec[k]
        data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
data = data %>% filter(sigma_sq == 1 & phi == 0.7)
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt = c('Linear-spatial', 'GAM-latlon', 'RFGLS', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
p = ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") + ylab("RMSE") + 
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
  print(p)
#figname = paste0(type, '_', func, '_mtd', method, '_vs_', class, '.png')
#ggsave(figname, width = 8, height = 6)
}

```
```{r}
figname = paste0('RMSE_dim5_main.png')
ggsave(figname, width = 8, height = 6)
```

```{r}
type = 'RMSE'
func = 'friedman'
p = 5
date = '1125'
method = '1'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

namelist = list(c('BRISC', 'GAM_latlong', 'NN', 'NN_latlong', 'NNDK',  'NNGLS_krig'),
                c('BRISC', 'GAM', 'GAM_krig', 'GAMGLS', 'GAMGLS_krig', 'NNGLS_krig'),
                c('RF', 'RF_krig', 'RFGLS_krig','NNGLS_krig', 'NNGLS_krig'),
                c('NN', 'NN_latlong', 'NNDK', 'NN_krig', 'NNGLS_krig'))
classes = c('GAM', 'RF', 'NN')
for(i in 1:1){
  names = namelist[[i]]
  class = classes[i]
#names_alt = names
  names_alt = c('Linear-spatial', 'GAM-latlon', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_RFGLS_temp = read.csv(paste0(path, filename3))[, c('RF', 'RFGLS_krig')]
      colnames(df_RFGLS_temp) = c('RF', 'RFGLS')
      df_RFGLS_temp = melt(df_RFGLS_temp)
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt = c('Linear-spatial', 'GAM-latlon', 'RFGLS', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
p = ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") + ylab('RMSE') +
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
  print(p)
#figname = paste0(type, '_', func, '_mtd', method, '_vs_', class, '.png')
#ggsave(figname, width = 8, height = 6)
}

```
```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
type = 'RMSE'
func = 'friedman'
p = 5
date = '1201'
method = '2'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')
path2 = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/1125/')

namelist = list(c('BRISC', 'GAM_latlong', 'NN', 'NN_latlong', 'NNDK',  'NNGLS_krig'),
                c('BRISC', 'GAM', 'GAM_krig', 'GAMGLS', 'GAMGLS_krig', 'NNGLS_krig'),
                c('RF', 'RF_krig', 'RFGLS_krig','NNGLS_krig', 'NNGLS_krig'),
                c('NN', 'NN_latlong', 'NNDK', 'NN_krig', 'NNGLS_krig'))
classes = c('GAM', 'RF', 'NN')
for(i in 1:1){
  names = namelist[[i]]
  class = classes[i]
#names_alt = names
  names_alt = c('Linear-spatial', 'GAM-latlon', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_RFGLS_temp = read.csv(paste0(path2, filename3))[, c('RF', 'RFGLS_krig')]
      colnames(df_RFGLS_temp) = c('RF', 'RFGLS')
      df_RFGLS_temp = melt(df_RFGLS_temp)
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt = c('Linear-spatial', 'GAM-latlon', 'RFGLS', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
p = ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") +  ylab('RMSE') +
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
  print(p)
#figname = paste0(type, '_', func, '_mtd', method, '_vs_', class, '.png')
#ggsave(figname, width = 8, height = 6)
}

```

```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
type = 'MISE'
func = 'p15'
p = 15
date = '1125'
method = '0'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'GAM', 'GAMGLS', 'RF', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'NN-nonspatial', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      
      data = rbind(data, df_temp)
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
ggplot(data_plt , aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") +
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
```
```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
type = 'lr_MISE'
func = 'p15'
p = 15
date = '1121'
method = '0'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'GAM', 'GAMGLS', 'RF', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'NN-nonspatial', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      
      data = rbind(data, df_temp)
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
df_RF = read.csv(paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/',
                        'Compare/RF_p155000.csv'))[,-1]
if(F){
  data = data %>% filter(variable != 'RF')
  data_RF = data.frame(variable = rep('RF', nrow(df_RF)), value = df_RF$MISE, 
                       sigma_sq = df_RF$sigma_sq, phi = round(df_RF$phi/sqrt(2),1), 
                       tau = df_RF$tau*100)
  data = rbind(data, data_RF)
}
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") +
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
```

```{r}
figname = paste0(type, '_', func, '_mtd', method, '_5000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
type = 'lr_RMSE'
func = 'p15'
p = 15
date = '1121'
method = '0'
sigma_sq_vec = c(1, 10)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

namelist = list(c('BRISC', 'GAM_latlong', 'NN', 'NN_latlong', 'NNDK',  'NNGLS_krig'),
                c('BRISC', 'GAM', 'GAM_krig', 'GAMGLS', 'GAMGLS_krig', 'NNGLS_krig'),
                c('RF', 'RF_krig', 'RFGLS_krig','NNGLS_krig', 'NNGLS_krig'),
                c('NN', 'NN_latlong', 'NNDK', 'NN_krig', 'NNGLS_krig'))
classes = c('GAM', 'RF', 'NN')
for(i in 1:1){
  names = namelist[[i]]
  class = classes[i]
#names_alt = names
  names_alt = c('Linear-spatial', 'GAM-latlon', 'NN-nonspatial','NN-latlon', 'NN-splines', 'NN-GLS')

data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      
      data = rbind(data, df_temp)
    }
  }
  
}
data = data[-1,]
data = data[complete.cases(data),]
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
p = ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) +
  xlab("tau %") + ylab("RMSE") + 
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
  print(p)
#figname = paste0(type, '_', func, '_mtd', method, '_vs_', class, '.png')
#ggsave(figname, width = 8, height = 6)
}

```

```{r}
figname = paste0(type, '_', func, '_mtd', method, '_5000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/')
df_RF = read.csv(paste0(path, 'RF_para_friedman2000.csv'))[,-1]

df_RF_plt = df_RF %>% group_by(sigma_sq, phi, tau, node_size) %>% summarize(MISE = min(MISE), sigma_sq = sigma_sq, phi = phi, tau = tau, node_size = node_size, n_tree_optim = n_tree[which.min(MISE)])

df_RF_plt %>% ggplot(aes(x = node_size, y = MISE, group = as.character(tau))) +
  geom_point(aes(color = as.character(tau))) + facet_grid(sigma_sq ~ phi)

#### sin 2000: sig1 n_tree:60, node:60, sig5 n_tree:60, node:60
#### sin 5000: sig1 n_tree:150, node:60, sig5 n_tree:150, node:150

#### friedman 2000: sig1 n_tree:60, node:60, sig5 n_tree:60, node:150
#### friedman 5000: sig1 n_tree:150, node:60, sig5 n_tree:150, node:150

df_RF = df_RF %>% group_by(sigma_sq, phi, tau) %>% summarize(n_tree_optim =n_tree[which.min(MISE)], node_size_optim = node_size[which.min(MISE)])
df_RF
```

```{r}
type = 'MISE'
func = 'p3'
p = 3
date = '1121'
method = '0'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'GAM', 'GAMGLS', 'RF', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'NN-nonspatial', 'NN-GLS')


data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
#print(list.files('./new_data'))
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      
      data = rbind(data, df_temp)
    }
  }
}
data = data[-1,]
data = data[complete.cases(data),]
df_RF = read.csv(paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/',
                        'Compare/RF_sin2000.csv'))[,-1]
if(T){
  data = data %>% filter(variable != 'RF')
  data_RF = data.frame(variable = rep('RF', nrow(df_RF)), value = df_RF$MISE, 
                       sigma_sq = df_RF$sigma_sq, phi = round(df_RF$phi/sqrt(2),1), 
                       tau = df_RF$tau*100)  #%>% filter(sigma_sq == 5)
  data = rbind(data, data_RF)
}
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) + 
  xlab("tau %") + 
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))

```

```{r}

```



