---
title: "Sim_MISE_5dim"
author: "Wentao Zhan"
date: "2022/3/9"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F, warning = FALSE, echo = TRUE)
```

## R Markdown

```{r, echo = FALSE}
library(tidyverse)
myreshape = function(data){
  MISE = as.vector(as.matrix(data))
  label = rep(colnames(data), each = nrow(data))
  return(data.frame(x = rep(1, nrow(data)*ncol(data)), MISE_log = log(MISE), label = label))
}

plots <- function(file_name, breaks = 10, ratio = 50){
  data = read.csv(file_name)[,-1]
  if ('Means' %in% colnames(data)){
    #p =  hist(data$Means, breaks = breaks, main = 'Hist of Means')
    data = data[,  names(data)!='Means']
  
  }
  id = (apply(data, 1, max)/apply(data, 1, min) < ratio)
  data = data[id, ]
  data_plt = myreshape(data)

  p1 = ggplot(data_plt, aes(x = label, y=MISE_log, fill=label)) + 
      geom_violin()

  p2 = ggplot(data_plt, aes(x = label, y=MISE_log, fill=label)) + 
      geom_boxplot()
  
  #p3 = hist(log(data$MISE_Test/data$MISE), breaks = breaks, main = 'Hist of log(GLS_test/OLS)')
  
  #print(p1)
  print(p2)
  
  res = list()
  res$median = apply(data, 2, median)
  res$id = id
  
  return(res)
}  

plots_theta <- function(file_name, theta, id, breaks = 40){
  data = read.csv(file_name)
  data = data[id,]
  
  par(mfrow=c(3,1))
  
  hist(data$sigma, breaks = breaks, main = paste0('sigma-sq = ', as.character(theta[1])))
  abline(v = theta[1], col="red", lwd=3, lty=2)
  
  hist(data$phi, breaks = breaks, main = paste0('phi = ', as.character(theta[2])))
  abline(v = theta[2], col="red", lwd=3, lty=2)
  
  hist(data$tau, breaks = breaks, main = paste0('tau-sq = ', as.character(theta[3])))
  abline(v = theta[3], col="red", lwd=3, lty=2)

}

plots_cor <- function(filename1, filename2, id,  result = 'MISE_Test'){
  data1 = read.csv(filename1)[id,]
  data2 = read.csv(filename2)[id,]
  
  data_new = data.frame(log(data1[[result]]), data2$sigma, data2$phi, data2$tau)
  colnames(data_new) = c(paste0('log(',result,')'), 'sigma_sq', 'phi', 'tau_sq')
  
  pairs(data_new)
}
```

# 5-dimensional case with 500 runs and seed.
```{r}
filename1 = '.\\data\\p5phi1sig1tau1mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi1sig1tau10mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi1sig1tau25mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi1sig5tau1mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi1sig5tau10mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi1sig5tau25mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi1sig10tau1mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi1sig10tau10mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi1sig10tau25mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```

```{r}
filename1 = '.\\data\\p5phi3sig1tau1mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi3sig1tau10mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi3sig1tau25mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi3sig5tau1mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi3sig5tau10mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi3sig5tau25mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi3sig10tau1mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi3sig10tau10mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi3sig10tau25mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```

```{r}
filename1 = '.\\data\\p5phi6sig1tau1mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi6sig1tau10mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi6sig1tau25mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi6sig5tau1mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi6sig5tau10mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi6sig5tau25mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi6sig10tau1mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi6sig10tau10mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
filename1 = '.\\data\\p5phi6sig10tau25mtd0.csv'

res = plots(filename1, breaks = 40)
res$median
```