---
title: "Simulation"
author: "Wentao Zhan"
date: "2022/7/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
library(tidyverse)
library(reshape)
library(RColorBrewer)

group.colors <- c(brewer.pal(9,"Oranges")[c(4, 8, 3)],
                  brewer.pal(9,"Greens")[c(5)], 
                  brewer.pal(9,"Blues")[c(4,8)])
names(group.colors) = c('NNGLS_oracle', 'NN-GLS', 'NN-nsp+kriging',
                        'NN-nonspatial',  
                        'NN-latlon', 'NN-spline')

group.colors <- c(brewer.pal(9,"YlOrRd")[c(3, 5, 7, 8)],
                       brewer.pal(9,"Reds")[c(3)],
                       brewer.pal(9,"Purples")[c(7)], 
                       brewer.pal(9,"Blues")[c(4,6,8)],
                       brewer.pal(9,"Greens")[c(5,8)])
names(group.colors) = c('NN-nonspatial', 'NN-latlon', 'NN-splines', 'NN-GLS',
                             'NNGLS_oracle',
                             'linear-spatial',
                             'GAM', 'GAM-latlon', 'GAMGLS',
                             'RF', 'RFGLS')

```

```{r}
date = '20231114'
method = '0'
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/friedman/', date, '/')

#names = c('BRISC', 'GAM', 'GAMGLS', 'RF', 'RFGLS', 'NN', 'NNGLS')
names = c('GAM', 'GAMGLS', 'NNGLS', 'rho')
#names = c('BRISC', 'GAM', 'GAMGLS', 'RF', 'NN', 'NNGLS')
names_alt =  c('GAM', 'GAMGLS', 'NN-GLS', 'rho')


data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma', 'phi', 'tau')
filename = 'phi3sig1tau1mtd0_MISE.csv'
df_temp = read.csv(paste0(path, filename))[, names]
colnames(df_temp) = names_alt
df_temp = melt(df_temp, id.vars = 'rho')
data = df_temp

data = data[complete.cases(data),]
data_plt = data %>% group_by(rho, variable) %>% summarise(value = median(value))
colnames(data_plt)[2:3] = c('Method', 'MISE') 
data_plt$MISE = (data_plt$MISE)^2
ggplot(data_plt, aes(x = rho, y = MISE)) + 
  geom_line(aes(group = Method, color = Method), size = 2) + 
  scale_color_manual(values=group.colors[names_alt]) +
  xlab("rho") + ylab("MISE") +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))

ggsave(paste0('friedman.png'), width = 10, height = 6)
```
