---
title: "Compare"
author: "Wentao Zhan"
date: "2022/3/9"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F, warning = FALSE, echo = TRUE)
```

## R Markdown
```{r, echo = FALSE}
library(tidyverse)
library(reshape)

library(RColorBrewer)
group.colors <- c(brewer.pal(9,"Oranges")[c(4, 8)],
                  brewer.pal(9,"Greens")[c(5)], 
                  brewer.pal(9,"Blues")[c(4,8)])
names(group.colors) = c('NNGLS_oracle', 'NN-GLS', 
                        'NN-nonspatial',  
                        'NN-latlon', 'NN-spline')


group.colors <- c(brewer.pal(9,"YlOrRd")[c(3, 4, 5, 8)],
                       brewer.pal(9,"Reds")[c(3)],
                       brewer.pal(9,"Purples")[c(6)], 
                       brewer.pal(9,"Blues")[c(4,6,7)],
                       brewer.pal(8,"Set2")[c(5)], brewer.pal(9,"Greens")[c(7)])
names(group.colors) = c('NN-nonspatial', 'NN-latlon', 'NN-splines', 'NN-GLS',
                             'NN-GLS_oracle',
                             'Linear-spatial',
                             'GAM', 'GAM-latlon', 'GAMGLS',
                             'RF', 'RFGLS')
```

# 1010: sample size 1000/500, ordered
# 1011: sample size 2000/1000, unordered, only for Friedman
# 1018: added CI and PI, size 1000/500
# 1024: updated GAMGLS and sparse implementation. (only 5 dim now)

# 1120: tried to add intercept
# 1121: use sample size 5000/2500

# 1-dimensional case with 100 runs and seed. (script for 1010 and 1011)
```{r}
type = 'MISE'
func = 'friedman'
p = 5
date = '1120'
path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename_BRISC = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_BRISC_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){
        print('Not found')
        next}
      df_temp = read.csv(paste0(path, filename))[,-1]
      print(nrow(df_temp))
      df_temp$BRISC = read.csv(paste0(path, filename_BRISC))$BRISC[1:nrow(df_temp)]
      
      write.csv(df_temp, paste0(path, filename))
    }
  }
}
```
```{r}
names = c("NNDK", "NN", "NNGLS_krig")
names_alt = c("NN-splines", "NN-nonspatial", "NN-GLS")
df_temp = read.csv('friedmanphi3sig1tau1mtd0flexible_NN_RMSE.csv')[,-1]
df_temp = df_temp[, c(names, 'n')]
df_temp = df_temp %>% filter(n >= 1000)
colnames(df_temp) = c(names_alt, 'n')
df_temp = melt(df_temp, id.vars = 'n')
data_plt = df_temp %>% group_by(n, variable) %>% summarise(value = median(value))
colnames(data_plt)[2:3] = c('Method', 'MISE')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = data_plt$MISE^2
ggplot(data_plt , aes(x = n, y = MISE)) + 
geom_line(aes(color = Method), size = 2) + 
scale_color_manual(values=group.colors[names_alt]) + 
xlab("sample size") + ylab('RMSE') + scale_x_log10() +
theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
      axis.text=element_text(size=12), axis.title=element_text(size=15),
      strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))

```
```{r}
names = c("NNDK", "NN", "NNGLS_krig")
names_alt = c("NN-splines", "NN-nonspatial", "NN-GLS")
df_temp = read.csv('friedmanphi1sig1tau1mtd0flexible_NN_RMSE.csv')[,-1]
df_temp = df_temp[, c(names, 'n')]
df_temp = df_temp %>% filter(n >= 1000)
colnames(df_temp) = c(names_alt, 'n')
df_temp = melt(df_temp, id.vars = 'n')
data_plt = df_temp %>% group_by(n, variable) %>% summarise(value = median(value))
colnames(data_plt)[2:3] = c('Method', 'MISE')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = data_plt$MISE^2
ggplot(data_plt , aes(x = n, y = MISE)) + 
geom_line(aes(color = Method), size = 2) + 
scale_color_manual(values=group.colors[names_alt]) + 
xlab("sample size") + ylab('RMSE') + scale_x_log10() +
theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
      axis.text=element_text(size=12), axis.title=element_text(size=15),
      strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))

```

```{r}
names = c("NNDK", "NN", "NNGLS_krig")
names_alt = c("NN-splines", "NN-nonspatial", "NN-GLS")
df_temp = read.csv('friedmanphi3sig1tau1mtd0fixed_NN_inc-domain_RMSE.csv')[,-1]
df_temp = df_temp[, c(names, 'n')]
df_temp = df_temp %>% filter(n >= 500)
colnames(df_temp) = c(names_alt, 'n')
df_temp = melt(df_temp, id.vars = 'n')
data_plt = df_temp %>% group_by(n, variable) %>% summarise(value = median(value))
colnames(data_plt)[2:3] = c('Method', 'MISE')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = data_plt$MISE^2
ggplot(data_plt , aes(x = n, y = MISE)) + 
geom_line(aes(color = Method), size = 2) + 
scale_color_manual(values=group.colors[names_alt]) + 
xlab("sample size") + ylab('RMSE') + scale_x_log10() +
theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
      axis.text=element_text(size=12), axis.title=element_text(size=15),
      strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))

figname = paste0('NN-increasing-domain', '.png')
ggsave(figname, width = 10, height = 6)

```

```{r}
names = c("NNDK", "NN_latlong", "NN", "NNGLS_krig")
names_alt = c("NN-splines", "NN-latlon", "NN-nonspatial", "NN-GLS")
df_temp = read.csv('friedmanphi1sig1tau1mtd0fixed_NN_inc-domain_RMSE.csv')[,-1]
df_temp = df_temp[, c(names, 'n')]
df_temp = df_temp %>% filter(n >= 500)
colnames(df_temp) = c(names_alt, 'n')
df_temp = melt(df_temp, id.vars = 'n')
data_plt = df_temp %>% group_by(n, variable) %>% summarise(value = median(value))
colnames(data_plt)[2:3] = c('Method', 'MISE')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = data_plt$MISE^2
ggplot(data_plt , aes(x = n, y = MISE)) + 
geom_line(aes(color = Method), size = 2) + 
scale_color_manual(values=group.colors[names_alt]) + 
xlab("sample size") + ylab('RMSE') + scale_x_log10() +
theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
      axis.text=element_text(size=12), axis.title=element_text(size=15),
      strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))

```

```{r}
names = c("NNDK", "NN", "NNGLS_krig")
names_alt = c("NN-splines", "NN-nonspatial", "NN-GLS")
df_temp = read.csv('friedmanphi3sig1tau1mtd0flexible_NN_fixed-domain_RMSE.csv')[,-1]
df_temp = df_temp[, c(names, 'n')]
df_temp = df_temp %>% filter(n >= 500)
colnames(df_temp) = c(names_alt, 'n')
df_temp = melt(df_temp, id.vars = 'n')
data_plt = df_temp %>% group_by(n, variable) %>% summarise(value = median(value))
colnames(data_plt)[2:3] = c('Method', 'MISE')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = data_plt$MISE^2
ggplot(data_plt , aes(x = n, y = MISE)) + 
geom_line(aes(color = Method), size = 2) + 
scale_color_manual(values=group.colors[names_alt]) + 
xlab("sample size") + ylab('RMSE') + scale_x_log10() +
theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
      axis.text=element_text(size=12), axis.title=element_text(size=15),
      strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))

figname = paste0('NN-fixed-domain', '.png')
ggsave(figname, width = 10, height = 6)

```

```{r}
names = c("NNDK", "NN", "NNGLS_krig")
names_alt = c("NN-splines", "NN-nonspatial", "NN-GLS")
df_temp = read.csv('friedmanphi1sig1tau1mtd0flexible_NN_fixed-domain_RMSE.csv')[,-1]
df_temp = df_temp[, c(names, 'n')]
df_temp = df_temp %>% filter(n >= 100)
colnames(df_temp) = c(names_alt, 'n')
df_temp = melt(df_temp, id.vars = 'n')
data_plt = df_temp %>% group_by(n, variable) %>% summarise(value = median(value))
colnames(data_plt)[2:3] = c('Method', 'MISE')
data_plt = data_plt %>% filter(Method %in% names_alt)
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = data_plt$MISE^2
ggplot(data_plt , aes(x = n, y = MISE)) + 
geom_line(aes(color = Method), size = 2) + 
scale_color_manual(values=group.colors[names_alt]) + 
xlab("sample size") + ylab('RMSE') + scale_x_log10() +
theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
      axis.text=element_text(size=12), axis.title=element_text(size=15),
      strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))


```
```{r}
n = 10000000
x = (1:n)/1000
y = sin(x)
sum((y - mean(y))^2)/n
```
```{r}
type = 'MISE'
func = 'sin'
p = 1
date = '1121'
method = '0'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'GAM', 'GAMGLS', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'NN-nonspatial', 'NN-GLS')


data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
#print(list.files('./new_data'))
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, df_temp)
    }
  }
}
data = data[-1,]
data = data[complete.cases(data),]
df_RF = read.csv(paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/',
                        'Compare/RF_sin5000.csv'))[,-1]
if(T){
  data = data %>% filter(variable != 'RF')
  data_RF = data.frame(variable = rep('RF', nrow(df_RF)), value = df_RF$MISE, 
                       sigma_sq = df_RF$sigma, phi = round(df_RF$phi/sqrt(2),1), 
                       tau = df_RF$tau*100)  #%>% filter(sigma_sq == 5)
  data = rbind(data, data_RF)
}
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = mean(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'RFGLS', 'NN-nonspatial', 'NN-GLS')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
data_plt$MISE = pmin(data_plt$MISE, 0.4*data_plt$sigma_sq)
ggplot(data_plt , aes(x = tau, y = MISE)) + 
geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
scale_fill_manual(values=group.colors[names_alt]) + 
xlab("tau %") + scale_y_sqrt() +
facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
      axis.text=element_text(size=12), axis.title=element_text(size=15),
      strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
#figname = paste0(type, '_', func, '_sigma', sigma_sq_temp, '_mtd', method, '_2000.png')
#ggsave(figname, width = 8, height = 4)
```
```{r}
figname = paste0(type, '_', func, '_mtd', method, '_5000.png')
ggsave(figname, width = 8, height = 4)
```

```{r}
type = 'MISE'
func = 'sin'
p = 1
date = '1125'
method = '1'
sigma_sq_vec = c(1, 5)
phi_vec = c(1, 3, 6)
tau_vec = as.character(c(1, 10, 25))
cols = c('tau', 'Method', 'MISE')

path = paste0('/Users/zhanwentao/Documents/Abhi/NN/Simulation/Compare/dim', 
              p, '/', date, '/')

names = c('BRISC', 'GAM', 'GAMGLS', 'RF', 'NN', 'NNGLS')
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'NN-nonspatial', 'NN-GLS')


data = data.frame(matrix(ncol = 5))
colnames(data) = c('variable', 'value', 'sigma_sq', 'phi', 'tau')
#print(list.files('./new_data'))
for(i in 1:length(sigma_sq_vec)){
  for(j in 1:length(phi_vec)){
    for(k in 1:length(tau_vec)){
      filename = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_', type, '.csv'), collapse = '')
      filename3 = paste0(c(func, 'phi', phi_vec[j], 'sig', sigma_sq_vec[i], 'tau', tau_vec[k], 'mtd', method, '_RFGLS20_', type, '.csv'), collapse = '')
      if(!(filename %in% list.files(path))){next}
      df_temp = read.csv(paste0(path, filename))[, names]
      df_RFGLS_temp = melt(read.csv(paste0(path, filename3))[, c('RF', 'RFGLS')])
      df_RFGLS_temp$sigma_sq = sigma_sq_vec[i]
      df_RFGLS_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_RFGLS_temp$tau = tau_vec[k]
      colnames(df_temp) = names_alt
      df_temp = melt(df_temp)
      df_temp$sigma_sq = sigma_sq_vec[i]
      df_temp$phi = round(phi_vec[j]/sqrt(2),1)
      df_temp$tau = tau_vec[k]
      data = rbind(data, rbind(df_temp, df_RFGLS_temp))
    }
  }
}
data = data[-1,]
data = data[complete.cases(data),]
data_plt = data %>% group_by(sigma_sq, phi, tau, variable) %>% summarise(value = median(value))
colnames(data_plt)[4:5] = c('Method', 'MISE') 
names_alt = c('Linear-spatial', 'GAM', 'GAMGLS', 'RF', 'RFGLS', 'NN-nonspatial', 'NN-GLS')
data_plt$Method = factor(data_plt$Method, levels = names_alt)
data_plt$MISE = (data_plt$MISE)^2
data_plt$MISE = pmin(data_plt$MISE, 0.4*data_plt$sigma_sq)
ggplot(data_plt, aes(x = tau, y = MISE)) + 
  geom_bar(aes(fill = Method), position = "dodge", stat="identity") + 
  scale_fill_manual(values=group.colors[names_alt]) + 
  xlab("tau %") + 
  facet_grid(sigma_sq ~ phi, scales = 'free', labeller = label_both) +
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))

```
```{r}
figname = paste0(type, '_', func, '_mtd', method, '_2000.png')
ggsave(figname, width = 8, height = 4)
```




