
```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F, warning = FALSE, echo = TRUE)

library(tidyverse)
library(reshape2)
```

```{r}
source('/Users/zhanwentao/Documents/Abhi/RF/utils.R')

sigma.sq = 1
phi = 4/sqrt(2)
tau = 0.01
tau.sq = sigma.sq*tau
theta_set = c('sigma.sq' = sigma.sq, 'tau.sq' = tau.sq, 'phi' = phi)

n = 250
set.seed(2023)
coords <- cbind(runif(n,0,10), runif(n,0,10))
coords = coords[order(rowSums(coords)),]

D <- as.matrix(dist(coords))
R <- exp(-phi*D)
w <- rmvn(1, rep(0,n), sigma.sq*R)
y <- rnorm(n, fxy(x) + w, sqrt(tau.sq))
cov = sigma.sq*R + diag(rep(tau.sq, n))
chol_cov = chol(cov)

det = eigen_max = eigen_min = NULL
for(m_neighbor in 2:100){
 chol = G_gen(coords, theta_set, m_neighbor) 
 
 E_sqrt = chol %*% t(chol_cov)
 E = t(E_sqrt) %*% E_sqrt
 det = c(det, det(E))
 eigen_max = c(eigen_max, norm(E, "2"))
 eigen_min = c(eigen_min, 1/norm(solve(E), "2"))
}

df = data.frame(Det = det, Eigen_max = eigen_max, Eigen_min = eigen_min)
write.csv(df, 'p5phi4sig1tau1n250_R.csv')
```

```{r}
data = read.csv('p5phi4sig1tau1n1000_py.csv')[,-1]
data$m_neighbor = 2:249

data = data %>% filter(m_neighbor <= 50)

data_plt = melt(data, id.vars = 'm_neighbor')

ggplot(data, aes(x = m_neighbor, y = 250 - log(Det))) + geom_line(size = 2) +
  ylab('KL divergence') + ggtitle('') +
   theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
ggsave('E_det.png', width = 8, height = 6)

ggplot(data, aes(x = m_neighbor, y = log(abs(Eigen_max-1), 10))) + geom_line() +
  ylab('log(|Eigen_max - 1|)') + ggtitle('Maximum eigenvalue') 

ggplot(data, aes(x = m_neighbor, y = log(abs(Eigen_min-1), 10))) + geom_line() +
  ylab('log(|Eigen_min-1|)') + ggtitle('Minimum eigenvalue') 

ggplot(data_plt[data_plt$variable!='Det',], 
       aes(x = m_neighbor, y = value, group = variable, color = variable)) +
  geom_line(size = 2) +
  ylab('Eigenvalues') + ggtitle('') + 
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 10))
ggsave('E.png', width = 8, height = 6)
```