---
title: "Simulation"
author: "Wentao Zhan"
date: "2022/7/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
library(tidyverse)
library(reshape)

library(RColorBrewer)
group.colors <- c(brewer.pal(9,"Oranges")[c(4, 8, 3)],
                  brewer.pal(9,"Greens")[c(5)], 
                  brewer.pal(9,"Blues")[c(4,8)])
names(group.colors) = c('NNGLS_oracle', 'NN-GLS', 'NN-nsp+kriging',
                        'NN-nonspatial',  
                        'NN-latlon', 'NN-spline')

```

```{r}
library(ggplot2)
data = read.csv('Estimation.csv')[,-1]
```

```{r}
ggplot(data[data$label == 'truth',])+
  geom_point(aes(x, y, color = z), size = 4) +
  #facet_wrap(~label, nrow = 1) +
  scale_color_gradient(low = "blue", high = "orange") + 
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 18))
ggsave('Estimation_truth.png', width = 8, height = 5)
```

```{r}
ggplot(data)+
  geom_point(aes(x, y, color = z), size = 4) +
  facet_wrap(~label, nrow = 1) +
  scale_color_gradient(low = "blue", high = "orange") + 
  theme(legend.text = element_text(size=15), legend.title = element_text(size=20),
        axis.text=element_text(size=12), axis.title=element_text(size=15),
        strip.text.x = element_text(size = 18))
ggsave('Estimation.png', width = 24, height = 6)
```

```{r}
ggplot(data) + geom_tile(aes(x, y, fill = z)) +
  facet_wrap(~label, nrow = 1) +
  coord_fixed(ratio = 1) +
  scale_fill_gradient(
    name = "Rainfall",
    low = "blue", high = "orange"
  ) +
  theme_bw()
```

```{r}
library(ggplot2)
data = read.csv('Prediction.csv')[,-1]
```

```{r}
ggplot(data[data$train == 'False', ])+
  geom_point(aes(x, y, color = z), size = 2) +
  facet_wrap(~label, nrow = 1) +
  scale_color_gradient(low = "blue", high = "orange") +
  theme_bw()
ggsave('Prediction.png', width = 20, height = 3)
```

```{r}
myreshape = function(data){
  MISE = as.vector(as.matrix(data))
  label = rep(colnames(data), each = nrow(data))
  return(data.frame(x = rep(1, nrow(data)*ncol(data)), RMSE_log = log(MISE), label = label))
}


plots <- function(file_name, breaks = 10, ratio = 50){
  data = read.csv(file_name)[,-1]
  if ('Means' %in% colnames(data)){
    #p =  hist(data$Means, breaks = breaks, main = 'Hist of Means')
    data = data[,  names(data)!='Means']
  
  }
  id = (apply(data, 1, max)/apply(data, 1, min) < ratio)
  data$DK_coord = data$DeepKriging
  data$DK_spline = data$DeepKriging_spline
  data$NNGLS_krig = data$NNGLS_kriging
  data$NN_krig = data$NN_kriging
  data = data[id, c('NN', 'NN_krig', 'DK_coord', 'DK_spline','NNGLS_krig')]
  #data = data[id, c('NN', 'DK_spline','NNGLS_krig')]
  colnames(data) = c('NN-nonspatial', 'NN-nsp+kriging', 'NN-latlon', 'NN-spline', 'NN-GLS')
  data_plt = myreshape(data)
  data_plt$Method = factor(data_plt$label, levels = c('NN-nonspatial', 'NN-nsp+kriging', 'NN-latlon', 'NN-spline', 'NN-GLS'))
  #data_plt$Method = factor(data_plt$label, levels = c('NN', 'DK_spline', 'NNGLS_krig'))

  p1 = ggplot(data_plt, aes(x = label, y=RMSE_log, fill=label)) + 
      geom_violin()

  p2 = ggplot(data_plt, aes(x = Method, y=RMSE_log, fill=Method)) + 
      geom_boxplot() + scale_fill_discrete(name = "Methods") + xlab('Methods') + #ylim(c(-1,1))+
    scale_fill_manual(values=group.colors[colnames(data)]) +
  theme(legend.text = element_text(size=20), legend.title = element_text(size=20),
        axis.text=element_text(size=15), axis.title=element_text(size=18))
  
  #p3 = hist(log(data$MISE_Test/data$MISE), breaks = breaks, main = 'Hist of log(GLS_test/OLS)')
  
  #print(p1)
  print(p2)
  
  res = list()
  res$median = apply(data, 2, median)
  res$id = id
  
  return(res)
}  

```

```{r}
data = read.csv(filename1)[,-1]
head(data)
colnames(data) = c('NN_kriging', 'NNGLS_kriging', 'NNGLS_kriging', 'NN', 'DeepKriging', 'DeepKriging_spline')

write.csv(data, filename1)
```

```{r}
filename1 = './data/RMSE_0704.csv'
data = read.csv(filename1)[,-1]
colnames(data) = c('NN_kriging', 'NNGLS_kriging', 'NNGLS_update_kriging', 'NN', 'DK', 'DK_spline')
write.csv(data, filename1)
```

```{r}
data = read.csv('./data/RMSE_rand.csv')[,-1]
subdata = data[,c('NN', 'NNGLS_update_20', 'NN_kriging', 'DK_spline')]
colnames(subdata) = c('NN', 'NNGLS', 'NN_kriging', 'DeepKriging')
write.csv(subdata, './data/RMSE_rand_sub.csv')
```

```{r}
filename1 = './data/RMSE_rand_sub.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
ggsave('Real_data_prediction.png', width = 8, height = 6)
```

```{r}
filename1 = './data/RMSE_rand.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
ggsave('Real_0605.png', width = 10, height = 6)
```

```{r}
filename1 = './data/RMSE_block10.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
ggsave('Real_0605_block10.png', width = 10, height = 6)
```

```{r}
filename1 = './data/RMSE_block6.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
ggsave('Real_0605_block6.png', width = 10, height = 6)
```

Data_by_day

```{r}
filename1 = './data/data_by_day/RMSE_0704.csv'

res = plots(filename1, breaks = 40)
res$median
```
```{r}
ggsave('Real_0704.png', width = 10, height = 6)
```

```{r}
filename1 = './data/data_by_day/RMSE_0628.csv'

res = plots(filename1, breaks = 40)
res$median

ggsave('Real_0628.png', width = 10, height = 6)
```
```{r}
filename1 = './data/data_by_day/RMSE_0618.csv'

res = plots(filename1, breaks = 40)
res$median

ggsave('Real_0618.png', width = 10, height = 6)
```

```{r}
filename1 = './data/data_by_day/RMSE_0618_block10.csv'

res = plots(filename1, breaks = 40)
res$median

ggsave('Real_0618_block10.png', width = 10, height = 6)
```

```{r}
filename1 = './data/data_by_day/RMSE_0618_block6.csv'

res = plots(filename1, breaks = 40)
res$median

ggsave('Real_0618_block6.png', width = 10, height = 6)
```
